In [3]:
import numpy as np

**ARRAY OPERATION**

*ARTHMATIC OPERATION*

In [7]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])


In [8]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [9]:
a1-a2

array([-5, -5, -5, -5, -5])

In [10]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [11]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [12]:
a1%a2

array([1, 2, 3, 4, 5])

In [13]:
a1//a2

array([0, 0, 0, 0, 0])

In [14]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

*Broadcasting*

In [16]:
l = [10,20,30,40]
arr= np.array(l)

In [20]:
arr+10

array([20, 30, 40, 50])

In [25]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [26]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

*DEEP AND SHALLOW COPY*

In [51]:
a =np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [52]:
slice = a[:5]
slice = slice*10
slice 

array([10, 20, 30, 40, 50])

In [53]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [54]:
 a[4:6]*10

array([50, 60])

In [55]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [56]:
a
b=a.copy()

In [57]:
b[0] = 90
b

array([90,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [58]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

**matric operation**

In [6]:
mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[5,6],[7,8]])

In [7]:
mat1

array([[1, 2],
       [3, 4]])

In [8]:
mat2

array([[5, 6],
       [7, 8]])

matrix multiplaction

In [9]:
mat1@ mat2

array([[19, 22],
       [43, 50]])

In [10]:
np.dot(mat1, mat2)

array([[19, 22],
       [43, 50]])

Transpose of matrix

In [12]:
mat1.T

array([[1, 3],
       [2, 4]])

**stacking array**

In [18]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])


virtical stack

In [19]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

hotizontali stack

In [21]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

column_stack

In [24]:
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

spliting array

In [26]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

horizontal split

In [28]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [29]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [31]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [37]:
a = np.vsplit(c,4)
a

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [38]:
for i in a :
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]


In [39]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]