In [1]:
import numpy as np

**Basic Array creation**

In [5]:
arr = np.array([1,2,3,4,5,6,])
arr

array([1, 2, 3, 4, 5, 6])

In [8]:
a = [1,2,3,4,5,6,"hello", 3.5]
a

[1, 2, 3, 4, 5, 6, 'hello', 3.5]

In [19]:
np.array(a)  

array(['1', '2', '3', '4', '5', '6', 'hello', '3.5'], dtype='<U32')

In [21]:
l = [[1,2,3,],[4,5,6],[7,8,9]];
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [22]:
np.array(l)   

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**ARRAY GENRETING FUNCTION**

In [24]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [27]:
arr = np.zeros((4,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [29]:
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
arr = np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

**RANDOM GENRATION FUNCTION**

In [33]:
np.random.rand(10)

array([0.95611776, 0.66617998, 0.94342055, 0.526923  , 0.95437607,
       0.85648053, 0.19185303, 0.02418439, 0.73945154, 0.69837766])

In [38]:
np.random.randn(10)

array([-0.88878807,  1.15506612,  1.7063519 ,  0.02310204,  1.87594684,
       -0.11869176,  0.36004389,  1.29055483,  0.06240924, -1.98518633])

In [39]:
np.random.randint(10,20,10)

array([12, 17, 10, 11, 16, 10, 14, 14, 15, 12], dtype=int32)

**Array attributes**

In [46]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
arr.shape

(3, 3)

In [48]:
arr.size

9

In [49]:
arr.dtype

dtype('int64')

**Array methods**

In [50]:
arr.min()

np.int64(1)

In [51]:
arr.max()

np.int64(9)

In [52]:
arr.sum()

np.int64(45)

In [53]:
np.sum(arr,axis = 0)

array([12, 15, 18])

In [54]:
np.sum(arr, axis =1)

array([ 6, 15, 24])

In [55]:
arr.mean()

np.float64(5.0)

In [56]:
arr.std()

np.float64(2.581988897471611)

In [57]:
arr.argmax()

np.int64(8)

In [58]:
 arr.argmin()

np.int64(0)

**Reshaping  and Resizing**

In [61]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [64]:
arr= arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])