In [1]:
import numpy as np

In [2]:
s = np.array( [
[5, 3, 4, 6, 7, 8, 9, 1, 2],
[6, 7, 2, 1, 9, 5, 3, 4, 8],
[1, 9, 8, 3, 4, 2, 5, 6, 7],

[8, 5, 9, 7, 6, 1, 4, 2, 3],
[4, 2, 6, 8, 5, 3, 7, 9, 1],
[7, 1, 3, 9, 2, 4, 8, 5, 6],

[9, 6, 1, 5, 3, 7, 2, 8, 4],
[2, 8, 7, 4, 1, 9, 6,3,5],
[3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [3]:
b=np.sum(s,axis = 1)
for i in b:
    if(i!=45):
        print("sudoko is not valid")
        break
    else:
        print("sudoko is valid")
        break

sudoko is valid


In [4]:
a= np.sum(s,axis = 0)
for i in a:
    if(i!=45):
        print("sudoko is not valid")
        break
    else:
        print("sudoko is valid")
        break

sudoko is valid


In [5]:
slice = s[:3,:3]
np.sum(slice)


np.int64(45)

In [6]:
slice = s[:3,3:6]
np.sum(slice)


np.int64(45)

In [7]:
slice = s[:3,6:]
np.sum(slice)

np.int64(45)

In [8]:
slice = s[3:6,:3]
np.sum(slice)

np.int64(45)

In [9]:
slice = s[3:6,3:6]
np.sum(slice)

np.int64(45)

In [10]:
slice = s[3:6,6:]
np.sum(slice)

np.int64(45)

In [11]:
slice = s[6:,:3]
np.sum(slice)

np.int64(45)

In [12]:
slice = s[6:,3:6]
np.sum(slice)

np.int64(45)

In [13]:
slice = s[6:,6:]
np.sum(slice)

np.int64(45)

using for loop

In [14]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [15]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array( [
[18, 85, 78], #student 1
[19, 92, 88], #student 2
[17, 76, 95], #student 3
[18, 65, 70], #student 4
[20, 90, 85]  #student 5

])


In [16]:
#get the shape of the matrix
np.shape(data)

(5, 3)

In [17]:
age= data[:,0]
np.average(age)

np.float64(18.4)

In [18]:
#extrate maths marks for all student 
math = data[:,1]
math

array([85, 92, 76, 65, 90])

In [19]:
#find the higiest marks in seience 
science = data[:,2]
np.max(science)



np.int64(95)

In [20]:
#Get details of the student who scored more than 90 in math
data[data[:,1]>=90]

array([[19, 92, 88],
       [20, 90, 85]])

In [21]:
# increase math maeks of all student by 5
inc = data[:,1]+5
inc

array([90, 97, 81, 70, 95])

In [22]:
#find how many student younger than 19
age =len(data[data[:,0]<19])
age

3

In [23]:
#calculate the average marks in each subject 
np.mean(data[:,1:],axis = 0)

array([81.6, 83.2])

In [24]:
#get data of student who scored at list 80 in both subject 
data[(data[:,1]>=80)&(data[:,2]>=80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [26]:
# Replace  all science marks <75 with 0
data[:,2][data[:,2]<75]=0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])